- .gitignore
- .vscode/launch.json
- README.md
- bot.py
- phases.py
- stream_handlers.py
This PR adds settings for vs code, quickstart instructions, and provides various minor fixes here and there
> Minor discord bot fixes

- README.md
- bot.py
- bot_config.py
- database.py
Also updated README.md
Rename rpcs3Bot to bot
> User framework + piracy filter initial

- .gitignore
- README.md
- bot.py
> Migration fixes

- .vscode/launch.json
- README.md
- api/config.py
- api/response.py
- bot.py
- log_analyzer.py
Changed what settings are being extracted from logs
Changed Japan country code
> Fixes before embeds

- bot.py
- log_analyzer.py
Also add more mappings to a user-friendly values
> Fix log analyzer when nothing was matched in a phase

- bot.py
original message will be deleted, and censored message will be reposted by bot
if piracy is detected in logs, original message with attachment will also be removed
> piracy checks on regular messages

- api/result.py
- bot.py
- bot_config.py
- log_analyzer.py
Fix compat search results formating
Fix antipiracy messages when bot doesn't have permissions to delete the offending message
Link rules in the anti-piracy message
Check for piracy triggers on message edit
Fix log parsing for older versions
Fix GPU info extraction (again)
> Various fixes for many different things

- api/result.py
- bot.py
- log_analyzer.py
- only query info for commercial product codes
- separate info parsing and result formatting
- use vulkan gpu info if available, else d3d one, and show it after the cpu info
- more tweaks to what settings to show
- do code format sanitization to prevent injections through modified logs
- case insensitive piracy checks
- do not execute piracy subcommands in public channels
- log parsing result as an embed (don't really like the result, so it's not used in this pr)
> New fixes & log results as embed

- api/request.py
- api/response.py
- api/utils.py
- bot.py
- log_analyzer.py
Use actual urlencode instead of html encoder (???)
Sanitize user input when showin compat search results
Truncate compat search text to 40 characters to prevent dos with giant strings
> Make bot search for Dragon's Crown finally, and prevent more injections

- bot.py
- log_analyzer.py
also fix thread scheduler parsing
> usable log analysis result as embed

- bot.py
- log_analyzer.py
Fix :cell_ok_hand: response
Fix AF Override: Disabled formatting
More flexible !top command
Indicate custom config usage
Fix product code lookup if there were more than 6 codes in message
> Annual fixes

- api/result.py
- log_analyzer.py
* Fix AF formatting (d'oh)
* Return log analysis if no product info was found, but say so explicitly
> Two small fixes for log parsing

- api/config.py
- api/result.py
- bot.py
- bot_utils.py
also freshen up `!top` examples
> fix product code lookup when api is in maintenance mode

- api/result.py
- bot.py
- math_utils.py
Fix !compat results formatting
Fix !top without parameters
Use plain text for product code lookup when in maintenance mode to be less obnoxious
> Fix some shit that I broke or forgot to fix earlier

- bot.py
- log_analyzer.py
Also added Frame Limit option back
> New feature: os detection

- log_analyzer.py
* Aspect Ratio
* Force CPU Blit
Also fix some capitalization
> Add new options to parsed data

- bot.py
- log_analyzer.py
* Try to parse last run from the logs
* Optimized memory usage by flushing buffer every 256 KB
* Indicate if log was too large and parsed settings could reflect not the last run
* Extract GPU manufacturer and driver version from OpenGL renderer
> Support logs with multiple runs

- bot.py
- database.py
Oops, reporter and reported users were swapped, my bad
Also add db upgrade error logs and user report generation
> Fix some issues after !warn overhaul

- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Warnings.ListGroup.cs
- CompatBot/EventHandlers/AntipiracyMonitor.cs
- CompatBot/EventHandlers/LogInfoHandler.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/LogsAsTextMonitor.cs
- CompatBot/EventHandlers/Starbucks.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/RolesExtensions.cs
- CompatBot/Utils/StringUtils.cs
Apparently discord decided to remove multiple spaces inside inline code blocks.
Also fixes some minor bugs and adds missing rap file detection in logs.
> New discord client fixes

- CompatBot/Commands/Attributes/LimitedToHelpChannel.cs
- CompatBot/Commands/Attributes/LimitedToSpamChannel.cs
- CompatBot/Database/Providers/ThumbnailProvider.cs
- CompatBot/ThumbScrapper/PsnScraper.cs
- CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
Also some other minor hotfixes and tweaks
> fix piracy check in logs; again

- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Psn.Check.cs
- CompatBot/Utils/DiscordClientExtensions.cs
- CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
More variety, but also restrict to bot spam as requested
> Update meme commands

- CompatBot/EventHandlers/LogInfoHandler.cs
Right now parsing the log blocks the event processing loop, so bot drops all commands until it's finished
> Let's fix this performance issue with log parsing

- CompatBot/EventHandlers/AntipiracyMonitor.cs
- CompatBot/EventHandlers/BotShutupHandler.cs
- CompatBot/EventHandlers/LogInfoHandler.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/EventHandlers/Starbucks.cs
- CompatBot/Program.cs
- CompatBot/Utils/RolesExtensions.cs
Also limit simultaneous log parsing to half the cores instead of N-1
Also more fun stuff
> Fix extracting enabled library list

- CompatBot/Commands/Antipiracy.cs
- CompatBot/Commands/Warnings.cs
- CompatBot/Utils/EmbedPager.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
- CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
- CompatBot/Utils/StringUtils.cs
do field paging in log parsing results
also cap report for missing licenses to 10 items max
note changed resolution in log report
> Fix missing raps report

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
> major, world-changing fixes

- CompatBot/Commands/Invites.cs
- CompatBot/Commands/Sudo.Fix.cs
- CompatBot/EventHandlers/DiscordInviteFilter.cs
> New hotfixes

- CompatBot/Commands/Attributes/RequiresWhitelistedRole.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Moderation.cs
- CompatBot/EventHandlers/NewBuildsMonitor.cs
- CompatBot/EventHandlers/Starbucks.cs
- CompatBot/Program.cs
- CompatBot/Utils/DiscordClientExtensions.cs
- CompatBot/Utils/EmbedPager.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* new `!report message` command to report messages
* updated log parsing results formatting
> Some quality of life updates

- CompatBot/Commands/Misc.cs
> Credit where credit is due

- CompatBot/Commands/Misc.cs
- CompatBot/CompatBot.csproj
- CompatBot/EventHandlers/LogAsTextMonitor.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
See [milestone 2.6](../milestone/2) for fixed issues
> Low effort easy features

- CompatBot/Commands/Explain.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Particularly, detect disc games installed as a pkg
> A couple of new log detections

- .gitignore
- CompatBot/Commands/Misc.cs
- CompatBot/CompatBot.csproj
- CompatBot/Config.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/RarHandler.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/SevenZipHandler.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
With this all combinations of RAR4, RAR5, LZMA, LZMA2, PPMd, and BZip2 streams in normal, block, and solid formats are supported
> Support log uploads in RAR and 7z formats

- CompatBot/Commands/Moderation.Audit.cs
Also adds a new command to dump all user names for manual audit
> Update name spoofing audit command group

- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Warnings.ListGroup.cs
- CompatBot/EventHandlers/NewBuildsMonitor.cs
- CompatBot/Program.cs
- CompatBot/Utils/StringUtils.cs
More workarounds for issues with compat api
> New command !latest cached

- CompatBot/Commands/CompatList.cs
Be smarter with the regular `!latest` command instead
> Remove !latest cached command

- CompatApiClient/CompatApiClient.csproj
- CompatBot/Commands/CompatList.cs
- CompatBot/CompatBot.csproj
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/EventHandlers/TableFlipMonitor.cs
- CompatBot/Program.cs
> Update dependencies and some fun stuff

- CompatBot/Commands/Psn.Check.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/EventHandlers/TableFlipMonitor.cs
- IrdLibraryClient/IrdFormat/IrdParser.cs
- IrdLibraryClient/IrdFormat/IsoHeaderParser.cs
- azure-pipelines.yml
Backported disc mastering issue fix from the disc dumper
> Fix potential issues with log checks against IRD files

- CompatApiClient/Utils/Utils.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Psn.Check.cs
- CompatBot/Config.cs
- CompatBot/EventHandlers/AntipiracyMonitor.cs
- CompatBot/EventHandlers/DiscordInviteFilter.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/Utils/DiscordClientExtensions.cs
- CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
> Prevent command abuse to workaround various filters

- CompatApiClient/Client.cs
- CompatApiClient/CompatApiClient.csproj
- CompatBot/Commands/CompatList.cs
- CompatBot/CompatBot.csproj
- CompatBot/Config.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
- IrdLibraryClient/IrdLibraryClient.csproj
- PsnClient/PsnClient.csproj
- Tests/Tests.csproj
* updated dependencies
* use time information to consider builds to be outdated
* note for `Mega` SPU Block Size option in addition to `Giga`
* note for another case of broken save file
> Use extra information from the new update info model

- CompatBot/Commands/BotMath.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Moderation.cs
- CompatBot/Program.cs
- CompatBot/Utils/CommandContextExtensions.cs
- CompatBot/Utils/DiscordClientExtensions.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- PsnClient/PsnClient.cs
* hooked the built-in math parser's help into `!math help` command
* improvements to `!roll dice` command with multiple throws and modifiers support
* small additions to log analyzer
* ability to save `!explain` text as a text file to preserve all formatting (or any message for that matter)
* ability to `!report` any message, in any channel, by passing a message link
> Some small features and fixes

- CompatBot/Commands/Explain.cs
When command overload is resolved incorrectly and then silently dropped as a result
> Workaround bug in command module

- CompatBot/Commands/Explain.cs
- CompatBot/EventHandlers/Greeter.cs
- CompatBot/Program.cs
Explanation for `motd` is used as a message. If this term is not defined, then nothing is sent.
> Ability to send greeting message to all new users

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
> Detect /root_host/ shenanigans

- AppveyorClient/AppveyorClient.csproj
- AppveyorClient/Client.cs
- AppveyorClient/POCOs/Artifact.cs
- AppveyorClient/POCOs/ArtifactInfo.cs
- AppveyorClient/POCOs/Build.cs
- AppveyorClient/POCOs/BuildInfo.cs
- AppveyorClient/POCOs/Job.cs
- AppveyorClient/POCOs/Project.cs
- CompatApiClient/Client.cs
- CompatApiClient/Utils/Utils.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Pr.cs
- CompatBot/CompatBot.csproj
- CompatBot/Config.cs
- CompatBot/EventHandlers/BotShutupHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/ResultFormatters/PrInfoFormatter.cs
- CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
- CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
- CompatBot/Utils/StringUtils.cs
- GithubClient/Client.cs
- GithubClient/GithubClient.csproj
- GithubClient/POCOs/PrInfo.cs
- GithubClient/POCOs/StatusInfo.cs
- discord-bot-net.sln
* accepts a number, will return general information for any valid PR
* accepts optional string filter
* will return general information + latest successful build link for appveyor if the match is exact
* will return list of matched PRs otherwise
> Implement !pr command

- AppveyorClient/Client.cs
- AppveyorClient/POCOs/Build.cs
- AppveyorClient/POCOs/BuildInfo.cs
- AppveyorClient/POCOs/HistoryInfo.cs
- CompatBot/Commands/Antipiracy.cs
- CompatBot/Commands/Attributes/TriggersTyping.cs
- CompatBot/Commands/BotMath.cs
- CompatBot/Commands/CommandsManagement.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/CustomBaseCommand.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Invites.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Moderation.Audit.cs
- CompatBot/Commands/Pr.cs
- CompatBot/Commands/Sudo.Bot.cs
- CompatBot/Commands/Sudo.Fix.cs
- CompatBot/Commands/Sudo.Mod.cs
- CompatBot/Commands/Warnings.ListGroup.cs
- CompatBot/Commands/Warnings.cs
- CompatBot/Config.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/EventHandlers/UsernameSpoofMonitor.cs
- CompatBot/Utils/DiscordClientExtensions.cs
- CompatBot/Utils/ResultFormatters/PrInfoFormatter.cs
- CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
- GithubClient/Client.cs
- GithubClient/POCOs/PrInfo.cs
* more reliable search for successful build link
* link builds for closed PRs
* link latest master build for merged PRs
* overhaul bot notifications for background work
> Improvements to !pr command

- AppveyorClient/Client.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Pr.cs
- CompatBot/Config.cs
- CompatBot/EventHandlers/GithubLinksHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
- GithubClient/Client.cs
* hopefully fix appveyor build linking cache issue
* message full github links for mentioned issues/PRs to get default embeds
* new `!stats` command, mostly to check up on github rate limits
> More improvements to PR linking

- AppveyorClient/Client.cs
- CompatBot/EventHandlers/AppveyorLinksHandler.cs
- CompatBot/EventHandlers/BotShutupHandler.cs
- CompatBot/EventHandlers/GithubLinksHandler.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/Program.cs
* support linking to issues by simply using #xxxx
* cache appveyor history information for build lookups from job ids
> Enhancments to github linking

- CompatBot/Commands/Pr.cs
- CompatBot/EventHandlers/BotShutupHandler.cs
- CompatBot/Utils/DateTimeEx.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
* relative time offset for master builds
* better guesstimate for when new master build will be available
* removed some emojis from the pool of reactions, as they're not supported by discord
> Minor quality of life improvements

- AppveyorClient/Client.cs
- CompatBot/Commands/Pr.cs
- CompatBot/EventHandlers/BotShutupHandler.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
* fix relative build time formatting for merged PRs
* new check for corrupted dumps
* typos and whatnot
> Small enhancements

- CompatBot/EventHandlers/BotShutupHandler.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/LogParsing/LogParser.PipeReader.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* stop dissing users with PSN version of Demon's Souls
* show GPU information in more cases
* fix vulkan driver version display for RADV
> More log parsing fixes

- CompatBot/Database/Providers/ThumbnailProvider.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
- CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
- PsnClient/PsnClient.cs
- PsnClient/PsnClient.csproj
* fix some log detections after cellAudio refactorings
* add tmdb as a game title provider fallback
> Maintenance update

- CompatBot/Commands/CompatList.cs
- CompatBot/Config.cs
- CompatBot/EventHandlers/GithubLinksHandler.cs
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/EventHandlers/NewBuildsMonitor.cs
- CompatBot/EventHandlers/PostLogHelpHandler.cs
- CompatBot/Program.cs
* moved `!c` and `!top` responses to spam channels
* improved new builds checks
* general betterment of different use cases
> Misc enhancements

- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Pr.cs
- CompatBot/CompatBot.csproj
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/NewBuildsMonitor.cs
- CompatBot/EventHandlers/PostLogHelpHandler.cs
- CompatBot/Utils/CommandContextExtensions.cs
- CompatBot/Utils/CompatApiResultUtils.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/StringUtils.cs
* fuzzy matches for `!explain`
* sort `!compat` results
* new and improved issue detections in log parser
* improvements to reduce bot spam in different scenarios
> Support fuzzy matches

- AppveyorClient/Client.cs
- AppveyorClient/POCOs/Build.cs
- CompatApiClient/POCOs/UpdateInfo.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/EventHandlers/PostLogHelpHandler.cs
- CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
- GithubClient/POCOs/PrInfo.cs
* mark builds as new in build announcement channel
* use actual build time for master builds
> Various tweaks

- CompatBot/Commands/E3.cs
- CompatBot/Config.cs
- CompatBot/Database/BotDb.cs
- CompatBot/Database/Migrations/BotDb/20190129194930_AddE3Schedule.Designer.cs
- CompatBot/Database/Migrations/BotDb/20190129194930_AddE3Schedule.cs
- CompatBot/EventHandlers/AntipiracyMonitor.cs
- CompatBot/Program.cs
- CompatBot/Utils/DateTimeEx.cs
- CompatBot/Utils/StringUtils.cs
* implements #194
* adds ability to recheck past messages for piracy
> !e3 command

- CompatBot/Commands/E3.cs
- CompatBot/Commands/Warnings.cs
- CompatBot/Utils/DiscordClientExtensions.cs
* new commands to manage e3 events
* try to fix `!warn list` for some users
> Misc updates

- CompatBot/Commands/Invites.cs
- CompatBot/Commands/Pr.cs
- CompatBot/EventHandlers/DiscordInviteFilter.cs
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
* improve game status inquiry handler again
* fix piracy context reporting in warnings
* detect blatant attempts to circumvent discord invite filter
* only use github CI statuses if everything else failed, as they're unreliable
> Various bugfixes

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
> Fix sorting with custom emoji

- CompatBot/Commands/E3.cs
- CompatBot/Database/BotDb.cs
- CompatBot/Database/Migrations/BotDb/20190205174241_ChangeE3ToGenericEvent.Designer.cs
- CompatBot/Database/Migrations/BotDb/20190205174241_ChangeE3ToGenericEvent.cs
Expand on the scheduling a bit to promote other events in-between E3s
> Generic event schedule, part 1

- CompatBot/Commands/E3.cs
- CompatBot/Commands/Events.cs
- CompatBot/Commands/EventsBaseCommand.cs
- CompatBot/Program.cs
* new `!event` group
* `!e3` is a special alias now
> Generic event schedule, part 2

- CompatBot/Commands/Invites.cs
- CompatBot/Utils/AsciiTable.cs
- CompatBot/Utils/StringUtils.cs
- Tests/StringUtilTests.cs
fixes some edge cases in table formatting
> Implement string trimming based on visible characters length

- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Warnings.ListGroup.cs
- CompatBot/Commands/Warnings.cs
- CompatBot/EventHandlers/UnknownCommandHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Should help the noobs who try to use `!explain abc` as `!abc` all the damn time
> Catch-all handler for unknown commands

- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/E3.cs
- CompatBot/Commands/Events.cs
- CompatBot/Commands/EventsBaseCommand.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Psn.Check.cs
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/EventHandlers/UnknownCommandHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/DiscordClientExtensions.cs
- CompatBot/Utils/DiscordEmbedBuilderExtensions.cs
- CompatBot/Utils/DiscordMessageExtensions.cs
- CompatBot/Utils/InteractivityExtensions.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
New or updated commands:
* `!events add`/`update`
* `!explain`
* `!some unknown command that people often use for explanations or game status lookups`
* various tweaks and fixes throughout to make bot more useful and less annoying
> Implement some interactive stuff

- Clients/IrdLibraryClient/IrdLibraryClient.csproj
- CompatBot/Commands/Misc.cs
- CompatBot/CompatBot.csproj
Applying monthly security updates to dependencies
> A special for <@259997001880436737> and <@94397591957024768>

- CompatBot/Commands/EventsBaseCommand.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* Shader compilation errors
* Intel iGPU notes
> New log detections

- CompatBot/Commands/Antipiracy.cs
- CompatBot/Commands/Converters/CustomDiscordChannelConverter.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Psn.Check.cs
- CompatBot/CompatBot.csproj
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/EventHandlers/UnknownCommandHandler.cs
- CompatBot/Utils/DiscordClientExtensions.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
This is mostly to fix #221:
* Support for upcoming firmware version reporting
* Notes on old weak CPUs
* Note for the log owner
* Antipiracy commands will require bot sudoer role now
* Other misc fixes
> Fixes and updates to the log parser

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/LogParsing/LogParser.StateMachineGenerator.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Sometimes found values could've been replaced with an empty string from a no-match :(
> Fix even more bugs in the log parser

- CompatBot/Commands/BaseCommandModuleCustom.cs
> I am a big dum-dum

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
- README.md
fix instructions for Google Drive API configuration
> Fix the issue with "Log was copied from UI"

- CompatBot/Commands/BaseCommandModuleCustom.cs
- CompatBot/Commands/BotStats.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/EventsBaseCommand.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Moderation.Audit.cs
- CompatBot/Commands/Sudo.Bot.cs
- CompatBot/CompatBot.csproj
- CompatBot/Config.cs
- CompatBot/Database/BotDb.cs
- CompatBot/Database/Migrations/BotDb/20190301155219_PersistentStats.Designer.cs
- CompatBot/Database/Migrations/BotDb/20190301155219_PersistentStats.cs
- CompatBot/Database/Providers/AmdDriverVersionProvider.cs
- CompatBot/Database/Providers/StatsStorage.cs
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/GoogleDriveHandler.cs
- CompatBot/EventHandlers/PostLogHelpHandler.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/EventHandlers/Starbucks.cs
- CompatBot/EventHandlers/UnknownCommandHandler.cs
- CompatBot/GlobalSuppressions.cs
- CompatBot/Program.cs
- CompatBot/ThumbScrapper/GameTdbScraper.cs
- CompatBot/Utils/CommandContextExtensions.cs
- CompatBot/Utils/MemoryCacheExtensions.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
- README.md
* support for `dotnet user-secrets` to configure the bot
* fixed many compiler warnings
* fixed log spam with exceptions on bot restart
* statistics persistence on update/restart
> Backend maintenance

- Clients/PsnClient/POCOs/App.cs
- Clients/PsnClient/POCOs/Container.cs
- Clients/PsnClient/PsnClient.cs
- CompatBot/Commands/BotStats.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Psn.Check.cs
- CompatBot/Commands/Psn.cs
- CompatBot/CompatBot.csproj
- CompatBot/Config.cs
- CompatBot/Database/BotDb.cs
- CompatBot/Database/DbImporter.cs
- CompatBot/Database/Migrations/ThumbnailDb/20190306154836_ThumbsColorCache.Designer.cs
- CompatBot/Database/Migrations/ThumbnailDb/20190306154836_ThumbsColorCache.cs
- CompatBot/Database/Providers/ScrapeStateProvider.cs
- CompatBot/Database/Providers/ThumbnailProvider.cs
- CompatBot/Database/ThumbnailDb.cs
- CompatBot/EventHandlers/NewBuildsMonitor.cs
- CompatBot/Program.cs
- CompatBot/Utils/ColorGetter.cs
- CompatBot/Utils/InteractivityExtensions.cs
- CompatBot/Utils/SandboxDetector.cs
- CompatBot/Utils/StringUtils.cs
- Tests/StarsFormatTest.cs
Actually, it's an alias for `!psn search`, but who reads release notes anyway.
Additionally, move settings databases from the git work dir to user profile.
Also fix quite a few issues throughout.
> The long awaited !download a game command

- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Psn.cs
- CompatBot/Database/Providers/StatsStorage.cs
- CompatBot/Utils/StringUtils.cs
* fix saving bot stats (properly this time)
* fix searching for games returning invalid results in rare cases
> Small fixes

- CompatBot/EventHandlers/UsernameZalgoMonitor.cs
- CompatBot/Program.cs
- CompatBot/Utils/DiscordClientExtensions.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- Tests/ZalgoTests.cs
No management stuff for now, only monitoring and reporting
> Zalgo display name detection

- CompatBot/EventHandlers/LogAsTextMonitor.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
- CompatBot/EventHandlers/PostLogHelpHandler.cs
- CompatBot/Utils/PoorMansTaskScheduler.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* frame limit for Nier
* wcb for Nier, DeS, and GoW3
* P5 settings
> Some additional notes for most popular games

- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Explain.cs
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* asura's wrath
* jojo games
* games that require motion controls
> More settings checks for more games

- Clients/CompatApiClient/CompatApiClient.csproj
- CompatBot/CompatBot.csproj
- CompatBot/EventHandlers/LogParsing/SourceHandlers/BaseSourceHandler.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/GoogleDriveHandler.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/MegaHandler.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/PastebinHandler.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
> Add some more game-specific log notes

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* detect most common patch combinations
* detect some combinations of using the old 60 fps patch
> Try to detect some cases of using 60 fps patch for p5

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
* text input for nier replicant
* move game patch notes to the general section
> More game-specific notes

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* fixed update checks for very very old logs
* check for most mobile intel cpus
> More checks for logs

- CompatBot/Commands/CommandsManagement.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Sudo.Fix.cs
- CompatBot/Commands/Warnings.cs
- CompatBot/Program.cs
Fixed a couple typos. That about it.
> I erabe to finish what has been forgotten

- CompatBot/Commands/Attributes/RequiresNotMedia.cs
- CompatBot/Commands/BaseCommandModuleCustom.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Instead of reviewing every command, I just ignore everything ¯\_(ツ)_/¯
> Prevent spam in #media

- CompatBot/EventHandlers/DiscordInviteFilter.cs
- CompatBot/EventHandlers/readme.md
- CompatBot/readme.md
> Making Talkashie proud

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/IrdSearchResultFormattercs.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
* show product code and game title in log when compat api is down
* detect multiline format of log filters
* notes for specific cache corruptions
> Miscellaneous updates

- CompatBot/EventHandlers/DiscordInviteFilter.cs
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/Program.cs
- CompatBot/Watchdog.cs
Fixed a bunch of unhandled exceptions and implemented a workaround for socket deadlock in discord client library
> Maintenance release

- CompatBot/Utils/Extensions/DiscordUserExtensions.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* extract additional OS information from newer builds
* base resolution notes for Scott Pilgrim
> Log analyzer updates

- CompatBot/Commands/Sudo.Bot.cs
- CompatBot/Commands/Warnings.cs
- CompatBot/Program.cs
Also fix user warning listing in public channels in some cases
> Attempt to reconnect to discord until it works

- Clients/AppveyorClient/Client.cs
- CompatBot/Commands/Pr.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
* fix time-related issues with appveyor api
* add some audio-related checks for log parser
> Minor updates

- CompatBot/Program.cs
> Disable psn scraping as it's broken right now

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
* approximate xfloat
* unimplemented syscalls
> New and updated log checks

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* Some notes for God of War games
* Explicit note for custom configuration
> Add some more notes for the log parser

- CompatBot/Commands/BotMath.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Psn.cs
* !math help
* !download
* !psn search
> Small command improvements

- Clients/CompatApiClient/CompatApiClient.csproj
- Clients/IrdLibraryClient/IrdLibraryClient.csproj
- CompatBot/Commands/Psn.cs
- CompatBot/CompatBot.csproj
- Tests/Tests.csproj
* Clamp the number of psn search results
* Update 3rd party dependencies
> Fix potential for abuse

- Clients/PsnClient/PsnClient.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/Program.cs
- CompatBot/ThumbScrapper/PsnScraper.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
> New checks for RPCS3 install in special places

- CompatBot/Commands/Misc.cs
Added quite a few Positive and Negative quotes for !8ball and !rate commands
> Extra charming and poopy quotes (8ball & rate)

- CompatBot/Commands/Cyberpunk2077.cs
- CompatBot/Commands/EventsBaseCommand.cs
- CompatBot/Program.cs
- CompatBot/Utils/Extensions/InteractivityExtensions.cs
> Wasting my life

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Test case: [RPCS3.log](https://github.com/RPCS3/discord-bot/files/3308509/RPCS3.log)
> Improve Nvidia GPU detection

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
* uncapped NieR
* vblank interval
* misc fixes for other checks
> New checks for recent new settings and patches

- Clients/CompatApiClient/CompatApiClient.csproj
- CompatBot/CompatBot.csproj
- Tests/Tests.csproj
- nuget.config
* new version of Aho-Corasick Trie with fixes for multi-code point characters
* new version of Discord client (includes support for Teams and a new nuget source)
quite big changes, so a separate pr just in case
> Update 3rd party dependencies

- CompatBot/EventHandlers/PostLogHelpHandler.cs
Adds `give log` as an option for log querying.
> add support for my broken english

- CompatBot/Commands/EventsBaseCommand.cs
- CompatBot/Commands/Explain.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Syscall.cs
- CompatBot/Commands/Warnings.ListGroup.cs
- CompatBot/CompatBot.csproj
- CompatBot/Database/BotDb.cs
- CompatBot/Database/Migrations/ThumbnailDb/20190807141221_SyscallInfo.Designer.cs
- CompatBot/Database/Migrations/ThumbnailDb/20190807141221_SyscallInfo.cs
- CompatBot/Database/Providers/SyscallInfoProvider.cs
- CompatBot/Database/ThumbnailDb.cs
- CompatBot/EventHandlers/GithubLinksHandler.cs
- CompatBot/EventHandlers/LogParsing/ArchiveHandlers/IArchiveHandler.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/LogParsing/LogParser.StateMachineGenerator.cs
- CompatBot/EventHandlers/LogParsing/POCOs/LogParseState.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/ISourceHandler.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/Extensions/CommandContextExtensions.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* You can search what games use specific syscall, or system module
* You can search what module and function specific game used
> Keep track of what games use what syscalls

- CompatBot/Commands/Syscall.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Also "fix" `!syscall` command for Juhn
> New log parser notes

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/GenericLinkHandler.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
* support direct links for logs on github and discord
* note on enabled mtrsx
> Minor log parsing update

- CompatBot/EventHandlers/LogParsing/ArchiveHandlers/RarHandler.cs
- CompatBot/EventHandlers/LogParsing/ArchiveHandlers/ZipHandler.cs
This removes size limitations for zip and rar archives
> Stream zip and rar logs

- CompatBot/Commands/Misc.cs
Dropping some despair to the rate command for hope to shine even brighter in the future!
> Hope & Despair (Quotes for Rate)

- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Moderation.cs
- CompatBot/Config.cs
- CompatBot/EventHandlers/Starbucks.cs
You can use new command `!badudpate` or react on the message itself with ⚠ emoji
> Ability to mark update announcement as a bad update

- CompatBot/EventHandlers/Starbucks.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Unfortunately there are such things as "booting through installed patch or game data"
> Nerf check for disc dumps inside /dev_hdd0/game/

- CompatBot/Commands/Attributes/readme.md
- CompatBot/Commands/ContentFilters.cs
- CompatBot/Commands/Converters/readme.md
- CompatBot/Commands/readme.md
- CompatBot/Database/Providers/readme.md
- CompatBot/Database/readme.md
- CompatBot/Program.cs
- README.md
Continuation of the project started in #276
> Code documentation, part deux

- Clients/CompatApiClient/Compression/CompressionMessageHandler.cs
- Clients/PsnClient/POCOs/Container.cs
- Clients/PsnClient/PsnClient.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Psn.Check.cs
- CompatBot/Utils/ResultFormatters/FwInfoFormatter.cs
Use `!firmware` to check for the latest available update
> Implement check for ps3 firmware update

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* more fps unlock checks
* better sections organization
* add game version information
> Updates to log analyzer

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
shit got broken with duplicate settings logging
> Fix ppu threads extractor

- CompatBot/Commands/BotStats.cs
- CompatBot/Commands/Psn.cs
- CompatBot/Config.cs
- CompatBot/Database/DbImporter.cs
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ColorGetter.cs
- CompatBot/Utils/PathUtils.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/SandboxDetector.cs
- CompatBot/Utils/SandboxType.cs
* check for file sync folders in logs
* update sandbox checks
> Update some checks

- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
* game autostart on boot
* forced double-buffered vsync
> New log checks

- Clients/GithubClient/POCOs/PrInfo.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/Pr.cs
- CompatBot/EventHandlers/UsernameSpoofMonitor.cs
- CompatBot/Utils/Extensions/StringUtils.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
- HomoglyphConverter/Normalizer.cs
- Tests/StringUtilTests.cs
* show more details about updates in announcements
* check for available game updates when checking logs
> Small improvements

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Watchdog.cs
Implements everything from #482
> Log analyzer updates for 2020

- CompatBot/Commands/Moderation.cs
- CompatBot/CompatBot.csproj
- CompatBot/EventHandlers/Starbucks.cs
- CompatBot/Utils/Extensions/DiscordClientExtensions.cs
> Downgrade discord client, because of reactions fetch bug

- CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
discord started to generate embeds for the forum links, so
> Fix compat result list

- CompatBot/EventHandlers/ProductCodeLookup.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
This doesn't work for general game compatibility lookups
> Indicate built-in emulator compatibility for classics in log parser

- CompatBot/Database/Providers/SyscallInfoProvider.cs
yet another break from ef core 3.0 changes
> Fix the syscall fix

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Should hopefully curb expectations when needed. Might need refinement when the time comes. Thanks to @xddxd for the idea.
> Extend AMD checks for mobile SKUs

- CompatBot/Config.cs
- CompatBot/Database/Providers/ContentFilter.cs
- CompatBot/EventHandlers/DeletedMessagesMonitor.cs
- CompatBot/EventHandlers/GithubLinksHandler.cs
- CompatBot/EventHandlers/LogParsing/ArchiveHandlers/GzipHandler.cs
- CompatBot/EventHandlers/LogParsing/ArchiveHandlers/PlainText.cs
- CompatBot/EventHandlers/LogParsing/ArchiveHandlers/RarHandler.cs
- CompatBot/EventHandlers/LogParsing/ArchiveHandlers/SevenZipHandler.cs
- CompatBot/EventHandlers/LogParsing/ArchiveHandlers/ZipHandler.cs
- CompatBot/EventHandlers/LogParsing/LogParser.PipeReader.cs
- CompatBot/Program.cs
- CompatBot/Utils/Extensions/DiscordClientExtensions.cs
- CompatBot/Utils/Extensions/DiscordMessageExtensions.cs
> Add attachment reupload for deleted messages

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
> Add notes for LBP games

- CompatBot/Commands/Minesweeper.cs
- CompatBot/CompatBot.csproj
- CompatBot/Program.cs
- CompatBot/Utils/ResultFormatters/IrdSearchResultFormatter.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Watchdog.cs
> Add minesweeper

- CompatBot/Utils/Extensions/StringUtils.cs
- Tests/StringUtilTests.cs
Workaround some logic issues until upstream fixes the underlying algorithm
> Fix fuzzy string matching

- Clients/GithubClient/POCOs/PrInfo.cs
- CompatBot/Commands/CompatList.cs
(cue some other edge case with false positives in the future)
> Post missing build info when master build was never even started

- CompatBot/Commands/ForcedNicknames.cs
- CompatBot/Commands/Fortune.cs
- CompatBot/Commands/Misc.cs
- CompatBot/CompatBot.csproj
- CompatBot/Database/Migrations/ThumbnailDb/20210302213749_FortuneTable.Designer.cs
- CompatBot/Database/Migrations/ThumbnailDb/20210302213749_FortuneTable.cs
- CompatBot/Database/ThumbnailDb.cs
- CompatBot/EventHandlers/TableFlipMonitor.cs
- CompatBot/Program.cs
- CompatBot/Utils/Extensions/DiceCoefficientOptimized.cs
- CompatBot/Utils/Extensions/StringUtils.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- Tests/StringUtilTests.cs
- fortunes.txt
> Make fun stuff less fun

- .config/dotnet-tools.json
- .gitignore
- Clients/CirrusCiClient/.graphqlrc.json
- Clients/CirrusCiClient/CirrusCi.cs
- Clients/CirrusCiClient/CirrusCiClient.csproj
- Clients/CirrusCiClient/POCOs/BuildInfo.cs
- Clients/CirrusCiClient/POCOs/ProjectBuildStats.cs
- Clients/CirrusCiClient/Queries/GetBuilds.graphql
- Clients/CirrusCiClient/schema.extensions.graphql
- Clients/CirrusCiClient/schema.graphql
- Clients/CompatApiClient/Utils/Statistics.cs
- Clients/GithubClient/Client.cs
- CompatBot/Commands/Converters/TextOnlyDiscordChannelConverter.cs
- CompatBot/Commands/Moderation.cs
- CompatBot/Commands/Pr.cs
- CompatBot/Commands/Sudo.Fix.cs
- CompatBot/Commands/Sudo.cs
- CompatBot/Commands/Vision.cs
- CompatBot/CompatBot.csproj
- CompatBot/EventHandlers/LogParsingHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/Extensions/AzureDevOpsClientExtensions.cs
- CompatBot/Utils/Extensions/DiscordMessageExtensions.cs
- CompatBot/Utils/PoorMansTaskScheduler.cs
- discord-bot-net.sln
* Add support for PR build linking to Cirrus-CI
* Add support for message replies in some commands
* Update Discord client library to newly released stable version (no more nightly builds!)
> Support for Cirrus-CI and replies

- Clients/PsnClient/POCOs/TitlePatch.cs
- Clients/PsnClient/PsnClient.cs
- CompatBot/Commands/Fortune.cs
- CompatBot/Commands/Psn.Check.cs
- CompatBot/Database/Migrations/ThumbnailDb/20210414183007_AddGameUpdateInfo.Designer.cs
- CompatBot/Database/Migrations/ThumbnailDb/20210414183007_AddGameUpdateInfo.cs
- CompatBot/Database/Migrations/ThumbnailDb/20210414190638_AddGameUpdateInfoTimestamp.Designer.cs
- CompatBot/Database/Migrations/ThumbnailDb/20210414190638_AddGameUpdateInfoTimestamp.cs
- CompatBot/Database/Providers/TitleUpdateInfoProvider.cs
- CompatBot/Database/ThumbnailDb.cs
- CompatBot/Program.cs
- CompatBot/Utils/Extensions/StringUtils.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
* save PSN title update information when updates are available
* periodically check if there are any recent updates for all known product codes
> Implement persistent game update info cache

- Clients/MediafireClient/Client.cs
- CompatBot/EventHandlers/LogParsing/SourceHandlers/MediafireHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/OpenSslConfigurator.cs
because mediafire content servers have shitty tls configuration
> Add openssl configuration check and add shitty ciphers if needed

- CompatBot/Commands/Misc.cs
- HomoglyphConverter/Normalizer.cs
> New 8-ball answers

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Nothing major, just some really small Grammar fixes.
> Grammar corrections

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
> Loosen regex check on rpcs3 build string, to allow local_build

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Warn about Giga spu.
Warn about Mega spu on des.
Fix audio backend warns.
> Log parsing updates

- .github/workflows/dotnet.yml
- CompatBot/Commands/BotStats.cs
- CompatBot/Commands/Hardware.cs
- CompatBot/Commands/Sudo.cs
- CompatBot/Program.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
* implements !hw stats command
* implements hw.db backup
* implements some misc features related to hw survey feature
* adds release build step in CI script
Fixes #861.
> Part 2 of implementing hw survey

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
also plz merge instead of squashing, it's annoying to rebase on every pr
> Move fx cleanup to where the actual cpu name parsing is done

- CompatBot/Database/Providers/HwInfoProvider.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
but limit updates to four times per day per user
> Add some checks so people would stop worrying over nothing

- CompatBot/Database/Providers/HwInfoProvider.cs
I'm smort and understand boolean logic
> Fix hw info collection

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
fixes log parsing for mgo2 custom build
> make stage optional in the first line of log

- Dockerfile
22.04 containers are available now
> Update sdk container

- Clients/CompatApiClient/CompatApiClient.csproj
- Clients/GithubClient/GithubClient.csproj
- CompatBot/Commands/BotStats.cs
- CompatBot/CompatBot.csproj
- CompatBot/Config.cs
- CompatBot/Utils/TimeParser.cs
- Dockerfile
- Tests/Tests.csproj
For some reason all time zone info is missing.
Also updated regular deps.
> Try to fix time zone info after upgrading the docker image

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Okay sorry about opening multiple PRs, I know I should just use `git amend` properly.
This is okay now?
Fixes https://github.com/RPCS3/discord-bot/issues/890
> Prevent "CPUs before Ryzen" message for Steam Deck

- Tests/MemoryCacheExtensionTests.cs
- Tests/Tests.csproj
This was meant to be a part of #913
> Honker plz

- Clients/GithubClient/GithubClient.csproj
- CompatBot/Commands/BaseApplicationCommandModuleCustom.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/SlashMisc.cs
- CompatBot/Program.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- discord-bot-net.sln
matches everything up to and including broadwell
tests: https://regex101.com/r/WNnROT/1
> Add Xeon model check for old CPUs

- .config/dotnet-tools.json
- Clients/CirrusCiClient/CirrusCiClient.csproj
- Clients/CompatApiClient/CompatApiClient.csproj
- Clients/GithubClient/GithubClient.csproj
- Clients/IrdLibraryClient/IrdLibraryClient.csproj
- Clients/PsnClient/PsnClient.csproj
- CompatBot/CompatBot.csproj
- CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- SourceGenerators/SourceGenerators.csproj
- Tests/Tests.csproj
You might probably want to wait for the new container build instead of pulling after merge immediately
> Fix some crust

- CompatBot/EventHandlers/ProductCodeLookup.cs
> Pretty useless change

- CompatBot/Commands/ContentFilters.cs
- CompatBot/Commands/DevOnly.cs
- CompatBot/Commands/EventsBaseCommand.cs
- CompatBot/Config.cs
- CompatBot/EventHandlers/Starbucks.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Technically new behavior is correct as \ufe0f indicator is required to override glyph to use emoji symbol instead of legacy plain text
> Fix discord fuckery with emoji

- Clients/GithubClient/GithubClient.csproj
- CompatBot/CompatBot.csproj
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Follow-up on #926, didn't notice it broke the sorting
> Fix note sorting in log analysis results

- CompatBot/Commands/Attributes/LimitedToHelpChannel.cs
- CompatBot/Commands/Attributes/RequiresBotSudoerRole.cs
- CompatBot/Commands/Attributes/RequiresSupporterRole.cs
- CompatBot/Commands/Attributes/RequiresWhitelistedRole.cs
- CompatBot/Commands/CompatList.cs
- CompatBot/Commands/ContentFilters.cs
- CompatBot/Commands/ForcedNicknames.cs
- CompatBot/Commands/Misc.cs
- CompatBot/Commands/Moderation.cs
- CompatBot/Commands/Vision.cs
- CompatBot/Commands/Warnings.ListGroup.cs
- CompatBot/Commands/Warnings.cs
- CompatBot/Database/Providers/ContentFilter.cs
- CompatBot/Database/Providers/HwInfoProvider.cs
- CompatBot/EventHandlers/BotReactionsHandler.cs
- CompatBot/EventHandlers/DeletedMessagesMonitor.cs
- CompatBot/EventHandlers/DiscordInviteFilter.cs
- CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
- CompatBot/EventHandlers/MediaScreenshotMonitor.cs
- CompatBot/EventHandlers/Starbucks.cs
- CompatBot/EventHandlers/UsernameSpoofMonitor.cs
- CompatBot/EventHandlers/UsernameValidationMonitor.cs
- CompatBot/EventHandlers/UsernameZalgoMonitor.cs
- CompatBot/Utils/Extensions/DiscordClientExtensions.cs
- CompatBot/Utils/Extensions/RolesExtensions.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Previously only client cache was searched, but now we will fetch the data from server if it's not there
> Fix member fetching

- CompatBot/Database/Providers/AmdDriverVersionProvider.cs
In case multiple driver releases have the same vulkan driver version, use the latest known update.
> Fix AMD driver version reporting a bit

- CompatBot/Commands/ContentFilters.cs
probably broke with d#+ update
> fix !filters add without argument

- .config/dotnet-tools.json
- .github/workflows/codeql-analysis.yml
- .github/workflows/dotnet.yml
- Clients/CirrusCiClient/CirrusCiClient.csproj
- Clients/CompatApiClient/CompatApiClient.csproj
- Clients/GithubClient/GithubClient.csproj
- Clients/IrdLibraryClient/IrdLibraryClient.csproj
- Clients/MediafireClient/MediafireClient.csproj
- Clients/OneDriveClient/OneDriveClient.csproj
- Clients/PsnClient/PsnClient.csproj
- Clients/YandexDiskClient/YandexDiskClient.csproj
- CompatBot/Commands/Pr.cs
- CompatBot/Commands/Sudo.Bot.cs
- CompatBot/CompatBot.csproj
- CompatBot/Program.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
- Dockerfile
- HomoglyphConverter/HomoglyphConverter.csproj
- HomoglyphConverter/confusables.txt
- README.md
- Tests/Tests.csproj
* Restored Azure DevOps checks for PR builds (didn't test time estimates and all the status combinations though) (#944)
* Added Intel Arc check (#945)
* Updated libraries
> Upgrade to .NET 8.0

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Added more hashes for games like MGS4, TLOU, DeS and GT5
> Add more PPU Hashes

- CompatBot/EventHandlers/ProductCodeLookup.cs
pretty useless change but there are some NPUO ids reported on compatibility list
> Add support for NPUO ids lookup

- CompatBot/Commands/Attributes/RequiresDm.cs
- CompatBot/Commands/Psn.Check.cs
- CompatBot/CompatBot.csproj
- CompatBot/Config.cs
- CompatBot/EventHandlers/ProductCodeLookup.cs
that got broken when the old bot account died
> Fix some minor stuff

- CompatBot/Database/Providers/ModProvider.cs
- CompatBot/Program.cs
- CompatBot/Utils/Extensions/DiscordClientExtensions.cs
Turns out downloading all member data is not fast
> Fix ~8 minute unavailability on bot restart

- Clients/GithubClient/Client.CI.cs
- Clients/GithubClient/Client.cs
- Clients/GithubClient/GithubClient.csproj
- CompatBot/Commands/Pr.cs
- CompatBot/Database/Providers/ContentFilter.cs
- CompatBot/EventHandlers/DiscordInviteFilter.cs
- CompatBot/EventHandlers/GithubLinksHandler.cs
- CompatBot/EventHandlers/LogParsingHandler.cs
- CompatBot/Program.cs
- CompatBot/Utils/Extensions/AzureDevOpsClientExtensions.cs
Also fix bot mention in user warning messages
> Implement PR build links for GitHub Actions artifacts

- CompatBot/EventHandlers/LogParsingHandler.cs
This should prevent the "rate limited" spam on every message when the bot is busy
> Try to fix "Log processing is rate limited" spam

- CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
> Rename ZCull Sync to ZCull Accuracy

- Clients/CirrusCiClient/CirrusCiClient.csproj
- Clients/CompatApiClient/CompatApiClient.csproj
- Clients/GithubClient/GithubClient.csproj
- Clients/IrdLibraryClient/IrdLibraryClient.csproj
- Clients/PsnClient/PsnClient.csproj
- CompatBot/CompatBot.csproj
- CompatBot/Database/BotDb.cs
- CompatBot/Database/DbImporter.cs
- CompatBot/Database/HardwareDb.cs
- CompatBot/Database/Providers/DiscLanguageProvider.cs
- CompatBot/Database/ThumbnailDb.cs
- CompatBot/EventHandlers/UsernameZalgoMonitor.cs
- SourceGenerators/SourceGenerators.csproj
- Tests/StringUtilTests.cs
- Tests/Tests.csproj
- Tests/ZalgoTests.cs
* Fixes for zalgo handling
* Upgraded packages
* Less debug spam in release configuration
> Maintenance and fixes

- CompatBot/Commands/Processors/CommandErroredHandler.cs
- CompatBot/Database/Providers/ContentFilter.cs
- CompatBot/EventHandlers/AntiSpamMessageHandler.cs
- CompatBot/Program.cs
* keep track and remove extra copies of the same message in multiple channels
* limited to 10 seconds
* sends DM to the user (once per detection)
* try to send DMs in certain circumstances
* if content filter has Kick action
* if error handler detects an old bot command
> Some anti-spam enhancements
