RPCS3/discord-bot

api/result.py, bot.py, bot_utils.py, log_analyzer.py
This will only change the display of single code queries from regular messages, not `!compat` searches
Examples:
=> Use embed for a single product code lookup result display

log_analyzer.py
Prevents it from pulling out the empty D3D adapter which seems to be the first one it encounters.
=> Fix GPU detection in logs

bot.py
Embed field cannot be empty, so just mention that it was log
=> Do not fail when reporting empty messages with logs attached

bot.py, database.py
In this PR:
* implemented !explain command group (show, add, update, remove)
* implemented !warn list subcommand to show full list of users with warnings
* implemented !warn for any user, including unknown / banned / kicked users
* made it so users can check their own warnings (without details, even in DM)
* implemented retroactive starbucks check on bot startup
* updated warning db model to support tracking of who issued the warning
* added more reactions from bot on different commands
=> Implement !explain and general commands cleanup

CompatBot/Commands/Explain.cs, CompatBot/Commands/Psn.Check.cs, CompatBot/Commands/Sudo.Bot.cs, CompatBot/Config.cs, CompatBot/EventHandlers/BotShutupHandler.cs, CompatBot/EventHandlers/LogInfoHandler.cs, CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs, CompatBot/EventHandlers/LogParsing/LogParser.PipeReader.cs, CompatBot/Utils/EmbedPager.cs, CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs, CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
* Fix updates check for games that have more than 25 patches available, thanks, GT5.
* Limit log parsing time to 15 seconds tops.
* Add another detection to the log parser for pad initialization issue with native ui.
=> A new round of fixes

CompatBot/Commands/Psn.Check.cs, CompatBot/Commands/Psn.cs, CompatBot/Database/Providers/AmdDriverVersionProvider.cs, CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs, CompatBot/EventHandlers/LogParsing/LogParser.StateMachineGenerator.cs, CompatBot/Program.cs, CompatBot/ThumbScrapper/GameTdbScraper.cs, CompatBot/ThumbScrapper/PsnScraper.cs, CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Thanks to additional logging from kd, we can now get the driver version from vulkan device information (still not as good as opengl for AMD cards).
Plus a couple of fixes for psn scraping
=> Show driver version for vulkan renderer

CompatBot/CompatBot.csproj, CompatBot/EventHandlers/LogParsing/LogParser.PipeReader.cs
don't tell the pipe the examined position to fix this?
also updated some deps
=> for some reason pipe reader decided to break on advance

CompatBot/EventHandlers/LogAsTextMonitor.cs, CompatBot/EventHandlers/LogParsingHandler.cs
When a user posts an error from RPCS3's log or uploads a log in .txt format the bot will now respond with instructions on how to upload the full RPCS3.log.gz file. This will help stop some needless back and forth between users.
=> Small changes to bot responses

CompatBot/Commands/Explain.cs
When update contains only text/image, keep current image/text respectively.
To remove one or another, use `!explain remove text/attachment`.
=> Make !explain update consistent

CompatBot/Commands/Attributes/LimitedToHelpChannel.cs, CompatBot/Commands/Attributes/LimitedToSpamChannel.cs, CompatBot/Commands/BaseCommandModuleCustom.cs, CompatBot/Commands/Explain.cs, CompatBot/Commands/Sudo.Mod.cs, CompatBot/Config.cs, CompatBot/EventHandlers/AppveyorLinksHandler.cs, CompatBot/EventHandlers/BotReactionsHandler.cs, CompatBot/EventHandlers/GithubLinksHandler.cs, CompatBot/EventHandlers/IsTheGamePlayableHandler.cs, CompatBot/EventHandlers/LogAsTextMonitor.cs, CompatBot/EventHandlers/LogParsingHandler.cs, CompatBot/EventHandlers/PostLogHelpHandler.cs, CompatBot/EventHandlers/ProductCodeLookup.cs, CompatBot/EventHandlers/TableFlipMonitor.cs, CompatBot/EventHandlers/UnknownCommandHandler.cs, CompatBot/Program.cs, CompatBot/Utils/DefaultHandlerFilter.cs, CompatBot/Utils/DiscordClientExtensions.cs
Doesn't work for `.help`, that would require #148
=> Mark command for deletion with the new `.` command prefix

CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs, CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
It only works for Intel and AMD drivers when using OpenGL renderer, but hey.
It can also tell the **minimum** version that supports said drivers, not the **actual** version (i.e. if you use win7 drivers on win8, etc).
=> Try to guess windows version from the driver version

CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs, CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs, CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Removed the message about missing health bars, fixed in rpcs3 PR #6415. Changed audio preference to buffering enabled with duration set to 20ms; had to add an "audio_buffer_duration" item to the log parser.
Please ignore the duplicated commits, notepad++ broke my formatting.
=> Changes to "JoJo's Bizarre Adventure: All Star Battle" recommended settings

.dockerignore, CompatBot/CompatBot.csproj, CompatBot/Config.cs, CompatBot/Database/DbImporter.cs, CompatBot/Program.cs, CompatBot/Properties/launchSettings.json, CompatBot/Utils/Extensions/StringUtils.cs, CompatBot/Utils/SandboxDetector.cs, CompatBot/Utils/TimeParser.cs, Dockerfile, README.md, Tests/IrdTests.cs, Tests/StarsFormatTest.cs, Tests/TimeParserTests.cs, azure-pipelines.yml, discord-bot-net.sln, docker-compose.example.yml
This pull request implements authoring and publishing of the bot docker image to [Docker Hub](https://hub.docker.com/r/13xforever/rpcs3-discord-bot).
The CI stuff is handled by [Azure Pipelines](https://dev.azure.com/rpcs3-bot/RPCS3%20Bot/_build?definitionId=1).
To run the bot properly, you'll have to map some volumes or paths for data storage, example docker-compose.yml is provided.
=> Docker image support

CompatBot/Commands/Misc.cs
For https://github.com/RPCS3/discord-bot/issues/117
=> Added more 8ball commands.

CompatBot/Commands/Misc.cs
Adding more replies to 8ball and rate answers for issue #117
=> Adding more replies to 8ball and rate answers 

CompatBot/Commands/ContentFilters.cs, CompatBot/Program.cs, CompatBot/Utils/TimeParser.cs
Apparently `TimeZoneInfo` no longer provides human readable names, at all
=> Workaround timezone information issues in dotnet core 3.0

Clients/CompatApiClient/CompatApiClient.csproj, CompatBot/Commands/Attributes/LimitedToOfftopicChannel.cs, CompatBot/Commands/Attributes/LimitedToSpamChannel.cs, CompatBot/Commands/Explain.cs, CompatBot/Commands/Pr.cs, CompatBot/Commands/Vision.cs, CompatBot/CompatBot.csproj, CompatBot/Config.cs, CompatBot/EventHandlers/DiscordInviteFilter.cs, CompatBot/EventHandlers/GithubLinksHandler.cs, CompatBot/EventHandlers/GlobalMessageCache.cs, CompatBot/EventHandlers/NewBuildsMonitor.cs, CompatBot/EventHandlers/PostLogHelpHandler.cs, CompatBot/EventHandlers/ProductCodeLookup.cs, CompatBot/EventHandlers/Starbucks.cs, CompatBot/Program.cs, CompatBot/Utils/BufferCopyStream.cs, CompatBot/Utils/Extensions/DiscordClientExtensions.cs, CompatBot/Utils/FixedLengthBuffer.cs
Trying to workaround the new Discord API call limits by keeping local cache of last N messages per channel
=> Channel history lookup overhaul

CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs, CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Remove recommendation to disable TSX when user has TSX-FA. No-longer needed after https://github.com/RPCS3/rpcs3/pull/9048
Add more games that are known to require WCB
Add check for TLoU, WCB is only required when not using MLAA patch
Add check for Killzone 3, WCB is only required when not using MLAA patch.
=> Update settings check

Clients/CompatApiClient/Client.cs, Clients/CompatApiClient/Formatters/CompatApiCommitHashConverter.cs, CompatBot/EventHandlers/ProductCodeLookup.cs
and try to show cached data when there's an error communicating with compat api
=> Workaround the bug that was unmasked after moving to new json serializer

Clients/MediafireClient/Client.cs, Clients/MediafireClient/MediafireClient.csproj, Clients/MediafireClient/POCOs/LinksResult.cs, CompatBot/CompatBot.csproj, CompatBot/EventHandlers/LogParsing/ArchiveHandlers/RarHandler.cs, CompatBot/EventHandlers/LogParsing/ArchiveHandlers/SevenZipHandler.cs, CompatBot/EventHandlers/LogParsing/ArchiveHandlers/ZipHandler.cs, CompatBot/EventHandlers/LogParsing/SourceHandlers/MediafireHandler.cs, CompatBot/EventHandlers/LogParsingHandler.cs, discord-bot-net.sln
Unfortunately official API requires apikey, and that has been discontinued for years, so resort to usual web page scraping. It seems to be working at low volume traffic.
=> Implement Mediafire log source handler

CompatBot/Commands/readme.md
- fixes paths in relative links
- fixes a broken syntax (see the `Psn` section
Do not merge right away, Github's web editor messed up the EOF, needs fixing (please do) or not giving a hoot.
=> Fix links in the compatbot/commands readme

CompatBot/Commands/BaseCommandModuleCustom.cs, CompatBot/Commands/BotStats.cs, CompatBot/Commands/CompatList.cs, CompatBot/Commands/Explain.cs, CompatBot/CompatBot.csproj, CompatBot/Database/BotDb.cs, CompatBot/Database/Migrations/BotDb/20220704163631_AddStatsBucketColumn.Designer.cs, CompatBot/Database/Migrations/BotDb/20220704163631_AddStatsBucketColumn.cs, CompatBot/Database/Providers/StatsStorage.cs, CompatBot/EventHandlers/IsTheGamePlayableHandler.cs, CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
* wrap everything inside the provider
* do hour-long buckets to workaround the long-standing issue of sticky data bias
* remove stale data on stats restore instead of nuking-n-paving on every stat save
=> Update handling of bot usage stats

CompatBot/Utils/Extensions/MemoryCacheExtensions.cs
Apparently MemoryCache class was changed in .NET 7 and I didn't trigger the check on local instance
=> Fix cache extension methods

Clients/IrdLibraryClient/IrdClient.cs, CompatBot/Utils/ResultFormatters/IrdSearchResultFormatter.cs
#952
Rewritten ird command to use more API based approach fetch from DB that has much more IRD files available.
IRD source: https://flexby420.github.io/playstation_3_ird_database/
=> Update ird command

CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs, CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Some info was outdated and missing for some games like which games require PPU interpreter to work, which need disabled vertex cache etc.
=> Update few lists of games ids for x setting and simillar

Clients/IrdLibraryClient/IrdClient.cs
IRDs that have spaces and other characters like () didnt create a proper link
=> fix ird download link

Clients/IrdLibraryClient/IrdClient.cs, CompatBot/Utils/ResultFormatters/IrdSearchResultFormatter.cs, Tests/UriFormattingTests.cs
Initial implementation was breaking discord link formatting, and the attempted fix broke links with relative paths.
This version should fix both cases, and comes with some tests for known issues.
=> Properly escape ird download links without corrupting relative paths

CompatBot/Database/Providers/ContentFilter.cs
Apparently discord gateway is randomly sending events for ancient stuff from time to time.
=> Suppress bot replies for old messages

CompatBot/Watchdog.cs
Looked at the recent logs, and I think it's safe to immediately restart in case this event is logged.
=> Try to fix dead bot issue in one new case

CompatBot/Commands/Misc.cs, CompatBot/Commands/Processors/CommandErroredHandler.cs, CompatBot/Commands/Psn.Check.cs, CompatBot/Commands/Warnings.ContextMenus.cs, CompatBot/Commands/Warnings.cs, CompatBot/Config.cs, CompatBot/Database/Providers/ContentFilter.cs, CompatBot/EventHandlers/DiscordInviteFilter.cs, CompatBot/EventHandlers/LogParsingHandler.cs, CompatBot/EventHandlers/ProductCodeLookup.cs, CompatBot/EventHandlers/Starbucks.cs, CompatBot/Program.cs
- Reply to original message when using warn context menu on a message
- Restore bot muting with emoji reaction
- Better handling of unknown text commands
- Make `Check for updates` button on game info embed to work for everyone and change hint to work with slash commands by copy/paste
- Add bot config to use bulk command overwrite on startup
- Add mention of who warned the user in the user message
=> Hotfixes, part 2

Clients/CirrusCiClient/CirrusCiClient.csproj, Clients/CompatApiClient/CompatApiClient.csproj, Clients/GithubClient/GithubClient.csproj, Clients/IrdLibraryClient/IrdLibraryClient.csproj, Clients/PsnClient/PsnClient.csproj, CompatBot/Commands/DevOnly.cs, CompatBot/Commands/Explain.cs, CompatBot/Commands/ForcedNicknames.cs, CompatBot/Commands/MessageMenuCommands.cs, CompatBot/Commands/Warnings.ContextMenus.cs, CompatBot/CompatBot.csproj, CompatBot/EventHandlers/ProductCodeLookup.cs, SourceGenerators/ConfusablesSourceGenerator.cs, SourceGenerators/SourceGenerators.csproj, SourceGenerators/Win32ErrorsSourceGenerator.cs, Tests/Tests.csproj
There are two breaking changes in this one:
* Roslyn code generators require new incremental interface to be implemented
* D#+ broke how interactive components are added in message builders to accommodate v2 changes
=> Upgrading dependencies

.config/dotnet-tools.json, CompatBot/Commands/AutoCompleteProviders/ContentFilterAutoCompleteProvider.cs, CompatBot/Commands/AutoCompleteProviders/ExplainAutoCompleteProvider.cs, CompatBot/Commands/AutoCompleteProviders/InviteAutoCompleteProvider.cs, CompatBot/Commands/AutoCompleteProviders/ProductCodeAutoCompleteProvider.cs, CompatBot/Commands/AutoCompleteProviders/WarningAutoCompleteProvider.cs, CompatBot/Database/Migrations/ThumbnailDb/20250806100313_AddNoCaseCollationForGameTitle.Designer.cs, CompatBot/Database/Migrations/ThumbnailDb/20250806100313_AddNoCaseCollationForGameTitle.cs, CompatBot/Database/Providers/DiscLanguageProvider.cs, CompatBot/Database/ThumbnailDb.cs, CompatBot/Program.cs, CompatBot/Utils/Extensions/BotDbExtensions.cs, CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Some providers are using substring search in sqlite, which was broken due to implementation details and non-obvious behavior both on ef core, and sqlite side.
This makes the search case-insensitive.
Also fixes language code to country flag mapping logic for product code embeds by using region information from the product code.
=> Fix autocomplete providers for some slash commands
